FROM registry.redhat.io/ubi8

RUN yum update -y

RUN yum install -y bzip2 gcc zlib-devel zlib bzip2 bzip2-devel xz-libs xz-devel curl libcurl libcurl-devel hmaccalc openssl openssl-devel openssl-libs perl perl-Carp perl-File-Temp perl-Getopt-Long perl-Data-Dumper diffutils

RUN mkdir -p /broad/software/dotkit /broad/software/free/Linux/redhat_7_x86_64/pkgs /broad/software/build/utils




