name: Helm Chart linting V2

# This workflow triggers helm linting on PRs 
# This github action is broken into two dependent jobs.  This allows the first job to run 
#  under the runner OS environment.  And job 2 can run under a specific chart test docker 
#  container environment

# First job (prepare):
#  - determine which helm charts had updates
# Second job (lint):
#  - Run the Helm chart test/lint on any updated chart

on:
  pull_request:
    paths:
      - helm/**

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

    # Get list of files changed as part of PR
      - name: Get changed files
        id: changed-files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

    # process changed file list for any changes to helm charts under the helm directory
      - name: Get Chart list from changed files
        run: |
           # process list of changed files
           changed_files=$(echo "${{ steps.changed-files.outputs.all }}" | tr -d '[|]' | sed -e 's;,; ;g')
           chartlist=()
           # for each file see if it part of a helm chart
           for file in ${changed_files}
           do
              if echo $file | grep -qE "^helm/" 
              then
                 # file under helm directory get subdir name
                 subdir=$(echo $file | cut -d '/' -f2)
                 # ignore certain files
                 if [[ "${subdir}" != "ct.yaml" && "${subdir}" != "cr.yaml.ctmpl" ]]
                 then
                    # check if we seen this subdir before
                    if [[ ! " ${chartlist[@]} " =~ " ${subdir} " ]]
                    then
                        # add to changed chart list
                        chartlist+=( "${subdir}" )
                    fi
                 fi
             fi
           done
           # write to file
           echo "${chartlist[@]}" > changed-charts.txt

   # by archiving the list of updated charts allows second job access to the list
      - name: archive changed chart list
        uses: actions/upload-artifact@v2
        with:
          name: changed-charts
          path: changed-charts.txt

# JOB 2:
  lint:
    runs-on: ubuntu-latest
    needs: prepare
    container:
      image: quay.io/helmpack/chart-testing:v3.0.0-rc.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

    # download list of charts updated 
      - name: download changed chart list
        uses: actions/download-artifact@v2
        with:
          name: changed-charts

    # by dynamically updating ct.yaml with only the charts that were updated
    #  allows only linting changed charts
      - name: Add all charts to ct.yaml
        run: |
          for chart in $(cat changed-charts.txt)
          do
            echo "  - helm/${chart}" >> helm/ct.yaml
          done

        # We keep this around because it does version bump and
        # maintenance checks outside of what `helm lint` does.
        # It is separate because this needs to be at the top of
        # the repo, and it is cleaner to use the
        # working-directory directive below.
      - name: Chart Test Basic Lint
        run: ct lint --config helm/ct.yaml

        # These are each actually run by `ct lint`, but we want
        # to see their output and set arguments ourselves
        # (--strict). Because this GitHub Action is infrequently
        # run, duplicating the checks for the sake of keeping
        # this Action simple is worth it.
      - name: Helm Chart Strict Lint
        run: |
          # loop through updated charted list
          for chart in $(cat changed-charts.txt)
          do
              helm lint --strict --namespace default helm/${chart}
              yamale --schema /etc/ct/chart_schema.yaml helm/${chart}/Chart.yaml
              yamllint --config-file /etc/ct/lintconf.yaml --strict helm/${chart}/Chart.yaml helm/${chart}/values.yaml
          done
