name: Terraform Build

on:
  push:
    branches: 
      - master
    paths:
      - terraform/**
    

jobs:
  terraform_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create shell env file
      run: |
        env_files=$(find terraform/test -name \*.env -print)
        if [ ! -z "${env_files}" ]
        then
            for file in ${env_files}
            do
              IFS='=' ; cat ${file} | grep -Ev "^#" | while read key value
              do
                 echo "export ${key}=\"${value}\"" >> load.env
              done
            done
        fi

    # Runs a set of commands using the runners shell
    - name: Copy testing tfvars
      run: |
        tfvars=$(find terraform/test -name \*.tfvars -print)
        [ -f load.env ] && . load.env
        env

    # Create a new release
    - name: Tag a new release
      uses: mathieudutour/github-tag-action@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: terraform_
        
