name: Terraform Test

on:
  pull_request:
    branches: 
      - master
    paths:
      - terraform/**
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo perform tests
