name: Terraform Test

on:
  pull_request:
    branches: 
      - master
    paths:
      - terraform/**
    

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
