name: Terraform Build

on:
  push:
    branches: 
      - master
    paths:
      - terraform/**
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Build a terraform config
